/* AUTO-GENERATED from desktop/assets/model_manifest.json — do not edit by hand.
 * Regenerate with scripts/gen_manifest_header.py. Keep in sync with the
 * Android manifest (android/app/src/main/assets/model_manifest.json). */
#ifndef AXIS_EMBEDDED_MANIFEST_H
#define AXIS_EMBEDDED_MANIFEST_H

static const char AXIS_MANIFEST_JSON[] =
"{\n"
"  \"schemaVersion\": 1,\n"
"  \"models\": [\n"
"    {\n"
"      \"id\": \"qwen3.5-2b\",\n"
"      \"displayName\": \"Qwen3.5 2B (Q4_K_M)\",\n"
"      \"description\": \"Best quality. Latest-generation multilingual model (2026) with 201-language coverage, running fully offline via llama.cpp. Recommended on devices with 4 GB RAM or more.\",\n"
"      \"quantization\": \"Q4_K_M\",\n"
"      \"file\": \"Qwen3.5-2B-Q4_K_M.gguf\",\n"
"      \"url\": \"https://huggingface.co/unsloth/Qwen3.5-2B-GGUF/resolve/main/Qwen3.5-2B-Q4_K_M.gguf\",\n"
"      \"sha256\": \"aaf42c8b7c3cab2bf3d69c355048d4a0ee9973d48f16c731c0520ee914699223\",\n"
"      \"sizeBytes\": 1280835840,\n"
"      \"contextLength\": 2048,\n"
"      \"runtime\": \"llama.cpp\",\n"
"      \"license\": \"Apache-2.0 (Qwen3.5)\",\n"
"      \"languages\": [\n"
"        { \"code\": \"en\", \"name\": \"English\", \"nativeName\": \"English\" },\n"
"        { \"code\": \"id\", \"name\": \"Indonesian\", \"nativeName\": \"Bahasa Indonesia\" },\n"
"        { \"code\": \"jv\", \"name\": \"Javanese\", \"nativeName\": \"Basa Jawa\", \"script\": \"Latin\" },\n"
"        { \"code\": \"su\", \"name\": \"Sundanese\", \"nativeName\": \"Basa Sunda\", \"script\": \"Latin\" },\n"
"        { \"code\": \"ms\", \"name\": \"Malay\", \"nativeName\": \"Bahasa Melayu\" },\n"
"        { \"code\": \"tl\", \"name\": \"Filipino\", \"nativeName\": \"Filipino\" },\n"
"        { \"code\": \"ja\", \"name\": \"Japanese\", \"nativeName\": \"日本語\", \"script\": \"Japanese\" },\n"
"        { \"code\": \"ko\", \"name\": \"Korean\", \"nativeName\": \"한국어\", \"script\": \"Korean\" },\n"
"        { \"code\": \"zh\", \"name\": \"Chinese (Simplified)\", \"nativeName\": \"简体中文\", \"script\": \"Chinese\" },\n"
"        { \"code\": \"es\", \"name\": \"Spanish\", \"nativeName\": \"Español\" },\n"
"        { \"code\": \"fr\", \"name\": \"French\", \"nativeName\": \"Français\" },\n"
"        { \"code\": \"de\", \"name\": \"German\", \"nativeName\": \"Deutsch\" },\n"
"        { \"code\": \"it\", \"name\": \"Italian\", \"nativeName\": \"Italiano\" },\n"
"        { \"code\": \"pt\", \"name\": \"Portuguese\", \"nativeName\": \"Português\" },\n"
"        { \"code\": \"ru\", \"name\": \"Russian\", \"nativeName\": \"Русский\", \"script\": \"Cyrillic\" },\n"
"        { \"code\": \"uk\", \"name\": \"Ukrainian\", \"nativeName\": \"Українська\", \"script\": \"Cyrillic\" },\n"
"        { \"code\": \"cs\", \"name\": \"Czech\", \"nativeName\": \"Čeština\" },\n"
"        { \"code\": \"ro\", \"name\": \"Romanian\", \"nativeName\": \"Română\" },\n"
"        { \"code\": \"el\", \"name\": \"Greek\", \"nativeName\": \"Ελληνικά\", \"script\": \"Greek\" },\n"
"        { \"code\": \"ar\", \"name\": \"Arabic\", \"nativeName\": \"العربية\", \"script\": \"Arabic\" },\n"
"        { \"code\": \"fa\", \"name\": \"Persian\", \"nativeName\": \"فارسی\", \"script\": \"Arabic\" },\n"
"        { \"code\": \"he\", \"name\": \"Hebrew\", \"nativeName\": \"עברית\", \"script\": \"Hebrew\" },\n"
"        { \"code\": \"hi\", \"name\": \"Hindi\", \"nativeName\": \"हिन्दी\", \"script\": \"Devanagari\" },\n"
"        { \"code\": \"bn\", \"name\": \"Bengali\", \"nativeName\": \"বাংলা\", \"script\": \"Bengali\" },\n"
"        { \"code\": \"ur\", \"name\": \"Urdu\", \"nativeName\": \"اردو\", \"script\": \"Arabic\" },\n"
"        { \"code\": \"th\", \"name\": \"Thai\", \"nativeName\": \"ไทย\", \"script\": \"Thai\" },\n"
"        { \"code\": \"vi\", \"name\": \"Vietnamese\", \"nativeName\": \"Tiếng Việt\" },\n"
"        { \"code\": \"my\", \"name\": \"Burmese\", \"nativeName\": \"မြန်မာ\", \"script\": \"Myanmar\" },\n"
"        { \"code\": \"km\", \"name\": \"Khmer\", \"nativeName\": \"ខ្មែរ\", \"script\": \"Khmer\" },\n"
"        { \"code\": \"tr\", \"name\": \"Turkish\", \"nativeName\": \"Türkçe\" },\n"
"        { \"code\": \"nl\", \"name\": \"Dutch\", \"nativeName\": \"Nederlands\" },\n"
"        { \"code\": \"pl\", \"name\": \"Polish\", \"nativeName\": \"Polski\" }\n"
"      ],\n"
"      \"default\": true\n"
"    },\n"
"    {\n"
"      \"id\": \"qwen3.5-0.8b\",\n"
"      \"displayName\": \"Qwen3.5 0.8B (Q4_K_M)\",\n"
"      \"description\": \"Fast and light. Same latest-generation multilingual model (2026) as the 2B variant, tuned for snappy on-device translation on standard phones.\",\n"
"      \"quantization\": \"Q4_K_M\",\n"
"      \"file\": \"Qwen3.5-0.8B-Q4_K_M.gguf\",\n"
"      \"url\": \"https://huggingface.co/unsloth/Qwen3.5-0.8B-GGUF/resolve/main/Qwen3.5-0.8B-Q4_K_M.gguf\",\n"
"      \"sha256\": \"bd258782e35f7f458f8aced1adc053e6e92e89bc735ba3be89d38a06121dc517\",\n"
"      \"sizeBytes\": 532517120,\n"
"      \"contextLength\": 2048,\n"
"      \"runtime\": \"llama.cpp\",\n"
"      \"license\": \"Apache-2.0 (Qwen3.5)\",\n"
"      \"languages\": [\n"
"        { \"code\": \"en\", \"name\": \"English\", \"nativeName\": \"English\" },\n"
"        { \"code\": \"id\", \"name\": \"Indonesian\", \"nativeName\": \"Bahasa Indonesia\" },\n"
"        { \"code\": \"jv\", \"name\": \"Javanese\", \"nativeName\": \"Basa Jawa\", \"script\": \"Latin\" },\n"
"        { \"code\": \"su\", \"name\": \"Sundanese\", \"nativeName\": \"Basa Sunda\", \"script\": \"Latin\" },\n"
"        { \"code\": \"ms\", \"name\": \"Malay\", \"nativeName\": \"Bahasa Melayu\" },\n"
"        { \"code\": \"tl\", \"name\": \"Filipino\", \"nativeName\": \"Filipino\" },\n"
"        { \"code\": \"ja\", \"name\": \"Japanese\", \"nativeName\": \"日本語\", \"script\": \"Japanese\" },\n"
"        { \"code\": \"ko\", \"name\": \"Korean\", \"nativeName\": \"한국어\", \"script\": \"Korean\" },\n"
"        { \"code\": \"zh\", \"name\": \"Chinese (Simplified)\", \"nativeName\": \"简体中文\", \"script\": \"Chinese\" },\n"
"        { \"code\": \"es\", \"name\": \"Spanish\", \"nativeName\": \"Español\" },\n"
"        { \"code\": \"fr\", \"name\": \"French\", \"nativeName\": \"Français\" },\n"
"        { \"code\": \"de\", \"name\": \"German\", \"nativeName\": \"Deutsch\" },\n"
"        { \"code\": \"it\", \"name\": \"Italian\", \"nativeName\": \"Italiano\" },\n"
"        { \"code\": \"pt\", \"name\": \"Portuguese\", \"nativeName\": \"Português\" },\n"
"        { \"code\": \"ru\", \"name\": \"Russian\", \"nativeName\": \"Русский\", \"script\": \"Cyrillic\" },\n"
"        { \"code\": \"uk\", \"name\": \"Ukrainian\", \"nativeName\": \"Українська\", \"script\": \"Cyrillic\" },\n"
"        { \"code\": \"cs\", \"name\": \"Czech\", \"nativeName\": \"Čeština\" },\n"
"        { \"code\": \"ro\", \"name\": \"Romanian\", \"nativeName\": \"Română\" },\n"
"        { \"code\": \"el\", \"name\": \"Greek\", \"nativeName\": \"Ελληνικά\", \"script\": \"Greek\" },\n"
"        { \"code\": \"ar\", \"name\": \"Arabic\", \"nativeName\": \"العربية\", \"script\": \"Arabic\" },\n"
"        { \"code\": \"fa\", \"name\": \"Persian\", \"nativeName\": \"فارسی\", \"script\": \"Arabic\" },\n"
"        { \"code\": \"he\", \"name\": \"Hebrew\", \"nativeName\": \"עברית\", \"script\": \"Hebrew\" },\n"
"        { \"code\": \"hi\", \"name\": \"Hindi\", \"nativeName\": \"हिन्दी\", \"script\": \"Devanagari\" },\n"
"        { \"code\": \"bn\", \"name\": \"Bengali\", \"nativeName\": \"বাংলা\", \"script\": \"Bengali\" },\n"
"        { \"code\": \"ur\", \"name\": \"Urdu\", \"nativeName\": \"اردو\", \"script\": \"Arabic\" },\n"
"        { \"code\": \"th\", \"name\": \"Thai\", \"nativeName\": \"ไทย\", \"script\": \"Thai\" },\n"
"        { \"code\": \"vi\", \"name\": \"Vietnamese\", \"nativeName\": \"Tiếng Việt\" },\n"
"        { \"code\": \"my\", \"name\": \"Burmese\", \"nativeName\": \"မြန်မာ\", \"script\": \"Myanmar\" },\n"
"        { \"code\": \"km\", \"name\": \"Khmer\", \"nativeName\": \"ខ្មែរ\", \"script\": \"Khmer\" },\n"
"        { \"code\": \"tr\", \"name\": \"Turkish\", \"nativeName\": \"Türkçe\" },\n"
"        { \"code\": \"nl\", \"name\": \"Dutch\", \"nativeName\": \"Nederlands\" },\n"
"        { \"code\": \"pl\", \"name\": \"Polish\", \"nativeName\": \"Polski\" }\n"
"      ],\n"
"      \"default\": false\n"
"    },\n"
"    {\n"
"      \"id\": \"qwen2.5-0.5b-instruct\",\n"
"      \"displayName\": \"Qwen2.5 0.5B Instruct (compatible fallback)\",\n"
"      \"description\": \"Verified offline-capable GGUF model that runs on the same llama.cpp runtime. Translation quality is instruction-driven; useful on very low-end devices.\",\n"
"      \"quantization\": \"Q4_K_M\",\n"
"      \"file\": \"qwen2.5-0.5b-instruct-q4_k_m.gguf\",\n"
"      \"url\": \"https://huggingface.co/Qwen/Qwen2.5-0.5B-Instruct-GGUF/resolve/main/qwen2.5-0.5b-instruct-q4_k_m.gguf\",\n"
"      \"sha256\": \"74a4da8c9fdbcd15bd1f6d01d621410d31c6fc00986f5eb687824e7b93d7a9db\",\n"
"      \"sizeBytes\": 491400032,\n"
"      \"contextLength\": 2048,\n"
"      \"runtime\": \"llama.cpp\",\n"
"      \"license\": \"Apache-2.0 (Qwen license)\",\n"
"      \"languages\": [\n"
"        { \"code\": \"en\", \"name\": \"English\", \"nativeName\": \"English\" },\n"
"        { \"code\": \"id\", \"name\": \"Indonesian\", \"nativeName\": \"Bahasa Indonesia\" },\n"
"        { \"code\": \"ms\", \"name\": \"Malay\", \"nativeName\": \"Bahasa Melayu\" },\n"
"        { \"code\": \"ja\", \"name\": \"Japanese\", \"nativeName\": \"日本語\", \"script\": \"Japanese\" },\n"
"        { \"code\": \"ko\", \"name\": \"Korean\", \"nativeName\": \"한국어\", \"script\": \"Korean\" },\n"
"        { \"code\": \"zh\", \"name\": \"Chinese (Simplified)\", \"nativeName\": \"简体中文\", \"script\": \"Chinese\" },\n"
"        { \"code\": \"es\", \"name\": \"Spanish\", \"nativeName\": \"Español\" },\n"
"        { \"code\": \"fr\", \"name\": \"French\", \"nativeName\": \"Français\" },\n"
"        { \"code\": \"de\", \"name\": \"German\", \"nativeName\": \"Deutsch\" },\n"
"        { \"code\": \"it\", \"name\": \"Italian\", \"nativeName\": \"Italiano\" },\n"
"        { \"code\": \"pt\", \"name\": \"Portuguese\", \"nativeName\": \"Português\" },\n"
"        { \"code\": \"ru\", \"name\": \"Russian\", \"nativeName\": \"Русский\", \"script\": \"Cyrillic\" },\n"
"        { \"code\": \"ar\", \"name\": \"Arabic\", \"nativeName\": \"العربية\", \"script\": \"Arabic\" },\n"
"        { \"code\": \"hi\", \"name\": \"Hindi\", \"nativeName\": \"हिन्दी\", \"script\": \"Devanagari\" },\n"
"        { \"code\": \"th\", \"name\": \"Thai\", \"nativeName\": \"ไทย\", \"script\": \"Thai\" },\n"
"        { \"code\": \"vi\", \"name\": \"Vietnamese\", \"nativeName\": \"Tiếng Việt\" },\n"
"        { \"code\": \"tr\", \"name\": \"Turkish\", \"nativeName\": \"Türkçe\" },\n"
"        { \"code\": \"nl\", \"name\": \"Dutch\", \"nativeName\": \"Nederlands\" },\n"
"        { \"code\": \"pl\", \"name\": \"Polish\", \"nativeName\": \"Polski\" }\n"
"      ],\n"
"      \"default\": false\n"
"    }\n"
"  ]\n"
"}\n";

#endif /* AXIS_EMBEDDED_MANIFEST_H */
